# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3d_train_workflow.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18v3d_train_workflow.proto\x12\x1dprodia.v3d_train_workflow.api\"\x99\x04\n\x17V3DTrainWorkflowRequest\x12N\n\x03tos\x18\x01 \x01(\x0b\x32\x41.prodia.v3d_train_workflow.api.V3DTrainWorkflowRequest.V3dTosInfo\x12\x15\n\rworkspace_url\x18\x02 \x01(\t\x12\x11\n\tframe_url\x18\x03 \x01(\t\x12\x11\n\tcalib_url\x18\x04 \x01(\t\x12\x16\n\x0e\x62\x61\x63kground_url\x18\x05 \x01(\t\x12\x10\n\x08mask_url\x18\x06 \x01(\t\x12\x10\n\x08\x66low_url\x18\x07 \x01(\t\x12\x12\n\noutput_url\x18\x08 \x01(\t\x12\x10\n\x08gop_size\x18\t \x01(\x05\x12\x13\n\x0b\x66rame_start\x18\n \x01(\x05\x12\x14\n\x0c\x66rame_number\x18\x0b \x01(\x05\x12\x15\n\rcamera_number\x18\x0c \x01(\x05\x12\x14\n\x0cmatting_mode\x18\r \x01(\t\x12\x18\n\x10training_configs\x18\x0e \x01(\t\x12\x17\n\x0f\x64o_devignetting\x18\x0f \x01(\x08\x12\r\n\x05\x64\x65\x62ug\x18\x10 \x01(\x08\x12\x13\n\x0bop_versions\x18\x11 \x01(\t\x12\x18\n\x10render_views_url\x18\x12 \x01(\t\x1a\x46\n\nV3dTosInfo\x12\n\n\x02\x61k\x18\x01 \x01(\t\x12\n\n\x02sk\x18\x02 \x01(\t\x12\x10\n\x08\x65ndpoint\x18\x03 \x01(\t\x12\x0e\n\x06region\x18\x04 \x01(\t\"\'\n\x18V3DTrainWorkflowResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\xca\x01\n\x18V3DTrainWorkflowProgress\x12\x1d\n\x15\x66rame_extraction_done\x18\x01 \x01(\x08\x12\x18\n\x10\x63\x61libration_done\x18\x02 \x01(\x08\x12\x13\n\x0b\x66rame_start\x18\x03 \x01(\x05\x12\x14\n\x0c\x66rame_number\x18\x04 \x01(\x05\x12\x10\n\x08gop_size\x18\x05 \x01(\x05\x12\x19\n\x11\x66rames_done_total\x18\x06 \x01(\x05\x12\x1d\n\x15\x66rames_done_map_coded\x18\x07 \x03(\x05\x32\x99\x01\n\x0fProdiaWorkflows\x12\x85\x01\n\x10V3DTrainWorkflow\x12\x36.prodia.v3d_train_workflow.api.V3DTrainWorkflowRequest\x1a\x37.prodia.v3d_train_workflow.api.V3DTrainWorkflowResponse\"\x00\x42\x1fZ\x1dprodia/v3d_train_workflow/apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3d_train_workflow_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\035prodia/v3d_train_workflow/api'
  _V3DTRAINWORKFLOWREQUEST._serialized_start=60
  _V3DTRAINWORKFLOWREQUEST._serialized_end=597
  _V3DTRAINWORKFLOWREQUEST_V3DTOSINFO._serialized_start=527
  _V3DTRAINWORKFLOWREQUEST_V3DTOSINFO._serialized_end=597
  _V3DTRAINWORKFLOWRESPONSE._serialized_start=599
  _V3DTRAINWORKFLOWRESPONSE._serialized_end=638
  _V3DTRAINWORKFLOWPROGRESS._serialized_start=641
  _V3DTRAINWORKFLOWPROGRESS._serialized_end=843
  _PRODIAWORKFLOWS._serialized_start=846
  _PRODIAWORKFLOWS._serialized_end=999
# @@protoc_insertion_point(module_scope)
