"""add video_format field to videos table

Revision ID: 02c018315f19
Revises: 7b85d191618c
Create Date: 2025-12-02 10:33:11.417198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02c018315f19'
down_revision: Union[str, Sequence[str], None] = '7b85d191618c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add video_format column
    op.add_column('videos', sa.Column('video_format', sa.String(), nullable=True))
    
    # Set default value for existing rows
    op.execute("UPDATE videos SET video_format = 'mp4' WHERE video_format IS NULL")
    
    # Note: SQLite doesn't support ALTER COLUMN to change nullable constraint
    # The column will remain nullable in SQLite, but the application will enforce non-null
    
    # Note: Other detected changes (NOT NULL constraints, foreign keys, dropped columns)
    # are ignored here as they were already handled manually or are not applicable to SQLite
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'video_format')
    # ### end Alembic commands ###
