"""add calibration and background tables

Revision ID: 33687d08c0df
Revises: c4e81b4e6eb5
Create Date: 2025-12-02 10:14:13.743093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33687d08c0df'
down_revision: Union[str, Sequence[str], None] = 'c4e81b4e6eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if tables exist before creating (for existing databases)
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()
    
    # Create calibrations table if it doesn't exist
    if 'calibrations' not in existing_tables:
        op.create_table(
            'calibrations',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('owner_id', sa.Integer(), nullable=False),
            sa.Column('camera_count', sa.Integer(), nullable=False, comment='相机数'),
            sa.Column('collection_time', sa.DateTime(), nullable=False, comment='采集时间'),
            sa.Column('tos_path', sa.String(), nullable=False, comment='tos路径'),
            sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_calibrations_id'), 'calibrations', ['id'], unique=False)
    
    # Create backgrounds table if it doesn't exist
    if 'backgrounds' not in existing_tables:
        op.create_table(
            'backgrounds',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('owner_id', sa.Integer(), nullable=False),
            sa.Column('camera_count', sa.Integer(), nullable=False, comment='相机数'),
            sa.Column('collection_time', sa.DateTime(), nullable=False, comment='采集时间'),
            sa.Column('tos_path', sa.String(), nullable=False, comment='tos路径'),
            sa.Column('notes', sa.Text(), nullable=True, comment='备注'),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_backgrounds_id'), 'backgrounds', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_backgrounds_id'), table_name='backgrounds')
    op.drop_table('backgrounds')
    op.drop_index(op.f('ix_calibrations_id'), table_name='calibrations')
    op.drop_table('calibrations')
    # ### end Alembic commands ###
