"""add status to backgrounds

Revision ID: 83ab30652ad1
Revises: 02c018315f19
Create Date: 2025-12-02 17:07:10.334986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ab30652ad1'
down_revision: Union[str, Sequence[str], None] = '02c018315f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 因为 SQLite 不支持为已有行添加 NOT NULL 且无默认值的列，
    # 这里先创建可为空的列，填充默认值后再（概念上）视为非空。
    # 某些开发环境中该列可能已经存在，这里加检查避免重复添加。
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    columns = [col["name"] for col in inspector.get_columns("backgrounds")]
    if "status" not in columns:
        op.add_column(
            "backgrounds",
            sa.Column("status", sa.String(), nullable=True, server_default="uploading", comment="状态: uploading/ready/failed"),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("backgrounds", "status")
    # ### end Alembic commands ###
